version: "3.7"

services:
    # image project
    app:
        container_name: api-git-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: api-git/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        container_name: api-gitnginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel


    # redis
    redis:
        container_name: api-gitredis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge